version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
  - ./static:/app/static
  - ./media:/app/media
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
